site_name: "Ante-Hero TTRPG"
nav:
  - Home: index.md
  - Rules: 
      - Introduction: intro.md
      - Game Structure: game-structure.md
      - Dice System: dice.md
      - Charaters and Roles: characters.md
  - About: about.md
  - License: license.md
theme:
  name: simple-blog
  theme_style: dark
  sidebar: true
  navigation_depth: 6
  components:
    title: false
markdown_extensions:
  - toc:
      baselevel: 3
      permalink: ∞
